@startuml
class ExtraDataExtensions <<static>> {
    + {static} TryGetExtraData(container:IContainer<T>, key:string, data:object?) : bool
    + {static} TryGetExtraData(container:IContainer<T>, key:string, data:K?) : bool
    + {static} TryParseCommandArgs(container:IContainer<T>, output1:T1?) : bool
    + {static} TryParseCommandArgs(container:IContainer<T>, output1:T1?, output2:T2?) : bool
    + {static} TryParseCommandArgs(container:IContainer<T>, output1:T1?, output2:T2?, output3:T3?) : bool
    + {static} TryParseCommandArgs(container:IContainer<T>, output1:T1?, output2:T2?, output3:T3?, output4:T4?) : bool
}
@enduml
