@startuml
interface ISingletonUpdateHandler {
    + ShouldHandle(updater:IUpdater, update:Update) : bool
}
IUpdateHandler <|-- ISingletonUpdateHandler
ISingletonUpdateHandler --> "UpdateType" UpdateType
@enduml
