@startuml
abstract class UpdateWriterAbs {
    # UpdateWriterAbs()
    # UpdateWriterAbs(updater:IUpdater)
    <<internal>> SetUpdater(updater:IUpdater) : void
    + {abstract} ExecuteAsync(stoppingToken:CancellationToken) : Task
    # <<async>> EnqueueUpdateAsync(update:Update, cancellationToken:CancellationToken) : ValueTask
    <<internal>> {static} Create(updater:IUpdater) : UpdateWriterAbs
}
class "ILogger`1"<T> {
}
UpdateWriterAbs o-> "Updater" IUpdater
UpdateWriterAbs --> "BotClient" ITelegramBotClient
UpdateWriterAbs --> "Logger<IUpdater>" "ILogger`1"
UpdateWriterAbs --> "UpdaterOptions" UpdaterOptions
@enduml
