@startuml
class ScopedUpdateHandlersExtensions <<static>> {
    + {static} AddScopedUpdateHandler(updater:IUpdater, typeOfScopedHandler:Type, filter:Filter<TUpdate>?, updateType:UpdateType?, getT:Func<Update, TUpdate>?) : IUpdater
    + {static} AddScopedUpdateHandler(updater:IUpdater, filter:Filter<TUpdate>?, updateType:UpdateType?, getT:Func<Update, TUpdate?>?) : IUpdater
    + {static} AddScopedUpdateHandler(updater:IUpdater, updateType:UpdateType, filter:Filter<Message>?) : IUpdater
    + {static} AddScopedUpdateHandler(updater:IUpdater, updateType:UpdateType, filter:Filter<ChatMemberUpdated>?) : IUpdater
    + {static} AddScopedUpdateHandler(updater:IUpdater, filter:Filter<CallbackQuery>?) : IUpdater
    + {static} AddScopedUpdateHandler(updater:IUpdater, filter:Filter<InlineQuery>?) : IUpdater
    + {static} AddScopedUpdateHandler(updater:IUpdater, filter:Filter<ChatJoinRequest>?) : IUpdater
    + {static} AddScopedUpdateHandler(updater:IUpdater, filter:Filter<ChosenInlineResult>?) : IUpdater
    + {static} AddScopedUpdateHandler(updater:IUpdater, filter:Filter<Poll>?) : IUpdater
    + {static} AddScopedUpdateHandler(updater:IUpdater, filter:Filter<PollAnswer>?) : IUpdater
    + {static} AddScopedUpdateHandler(updater:IUpdater, filter:Filter<PreCheckoutQuery>?) : IUpdater
    + {static} AddScopedUpdateHandler(updater:IUpdater, filter:Filter<ShippingQuery>?) : IUpdater
}
@enduml
