@startuml
class MessageContainer <<sealed>> {
    <<internal>> MessageContainer(updater:IUpdater, shiningInfo:ShiningInfo<long, Update>, extraObjects:IReadOnlyDictionary<string, object>?)
}
class "UpdateContainerAbs`1"<T> {
}
"UpdateContainerAbs`1" "<Message>" <|-- MessageContainer
@enduml
