@startuml
class RawContainer <<sealed>> {
    + RawContainer(updater:IUpdater, shiningInfo:ShiningInfo<long, Update>, extraObjects:IReadOnlyDictionary<string, object>?)
    + ContainsKey(key:string) : bool
}
class "IReadOnlyDictionary`2"<T1,T2> {
}
class "ShiningInfo`2"<T1,T2> {
}
IUpdateContainer <|-- RawContainer
RawContainer --> "_extraObjects<string,object>" "IReadOnlyDictionary`2"
RawContainer --> "Updater" IUpdater
RawContainer --> "Container" Update
RawContainer --> "ShiningInfo<long,Update>" "ShiningInfo`2"
RawContainer --> "BotClient" ITelegramBotClient
@enduml
