@startuml
abstract class UpdateWriterServiceAbs {
    - _executingTask : Task?
    # UpdateWriterServiceAbs(updater:IUpdater)
    + <<virtual>> StartAsync(cancellationToken:CancellationToken) : Task
    + <<virtual>> <<async>> StopAsync(cancellationToken:CancellationToken) : Task
    + <<virtual>> Dispose() : void
}
UpdateWriterAbs <|-- UpdateWriterServiceAbs
IHostedService <|-- UpdateWriterServiceAbs
IDisposable <|-- UpdateWriterServiceAbs
UpdateWriterServiceAbs o-> "_stoppingCts" CancellationTokenSource
@enduml
