@startuml
class UpdaterServiceExtensions <<static>> {
    + {static} AddTelegramBotClient(services:IServiceCollection, botToken:string) : void
    + {static} AddTelegramUpdater(serviceDescriptors:IServiceCollection, botToken:string, updaterOptions:UpdaterOptions, builder:Action<UpdaterServiceBuilder>?, preUpdateProcessorType:Type?) : void
    + {static} AddTelegramUpdater(serviceDescriptors:IServiceCollection, telegramBot:ITelegramBotClient, updaterOptions:UpdaterOptions, builder:Action<UpdaterServiceBuilder>?, preUpdateProcessorType:Type?) : void
    + {static} AddTelegramUpdater(serviceDescriptors:IServiceCollection, updaterOptions:UpdaterOptions, builder:Action<UpdaterServiceBuilder>, preUpdateProcessorType:Type?) : void
    + {static} AddTelegramUpdater(serviceDescriptors:IServiceCollection, botToken:string, updaterOptions:UpdaterOptions, builder:Action<UpdaterServiceBuilder>?, preUpdateProcessorType:Type?) : void
    + {static} AddTelegramUpdater(serviceDescriptors:IServiceCollection, telegramBot:ITelegramBotClient, updaterOptions:UpdaterOptions, builder:Action<UpdaterServiceBuilder>?, preUpdateProcessorType:Type?) : void
    + {static} AddTelegramManualUpdater(serviceDescriptors:IServiceCollection, telegramBot:ITelegramBotClient, updaterOptions:UpdaterOptions, builder:Action<UpdaterServiceBuilder>?, preUpdateProcessorType:Type?) : void
    + {static} AddTelegramManualUpdater(serviceDescriptors:IServiceCollection, updaterOptions:UpdaterOptions, builder:Action<UpdaterServiceBuilder>, preUpdateProcessorType:Type?) : void
    + {static} AddTelegramManualUpdater(serviceDescriptors:IServiceCollection, botToken:string, updaterOptions:UpdaterOptions, builder:Action<UpdaterServiceBuilder>?, preUpdateProcessorType:Type?) : void
    + {static} <<async>> WriteUpdateAsync(updater:IUpdater, update:Update, cancellationToken:CancellationToken) : Task
}
@enduml
