@startuml
class CommandFilter {
    - _commands : string[]?
    + Prefix : char <<get>> = '/'
    + CommandFilter(commands:string[])
    + CommandFilter(prefix:char, commands:string[])
    + CommandFilter(prefix:char, argumentsMode:ArgumentsMode, commands:string[])
    + CommandFilter(command:string, prefix:char, argumentsMode:ArgumentsMode)
    + CommandFilter(command:string, options:CommandFilterOptions, prefix:char)
    + CommandFilter(commands:string[], prefix:char, options:CommandFilterOptions)
    + CommandFilter(deepLinkArg:string, joinArgsFormIndex:int?, caseSensitive:bool)
    + <<override>> TheyShellPass(_:IUpdater, input:Message) : bool
    + ToBotCommand() : IEnumerable<(int priority, BotCommand command)>
}
class "Filter`1"<T> {
}
"Filter`1" "<Message>" <|-- CommandFilter
CommandFilter o-> "Options" CommandFilterOptions
@enduml
