@startuml
abstract class "UserHasNumericStateFilter`1"<T> {
    + UserHasNumericStateFilter(userResolver:Func<T, User?>, stateKeeperName:string, state:int?)
}
class MessageUserHasNumericStateFilter <<sealed>> {
    + MessageUserHasNumericStateFilter(stateKeeperName:string, state:int?)
}
class CallbackQueryUserHasNumericStateFilter <<sealed>> {
    + CallbackQueryUserHasNumericStateFilter(stateKeeperName:string, state:int?)
}
class "Filter`1"<T> {
}
"Filter`1" "<T>" <|-- "UserHasNumericStateFilter`1"
"UserHasNumericStateFilter`1" "<Message>" <|-- MessageUserHasNumericStateFilter
"UserHasNumericStateFilter`1" "<CallbackQuery>" <|-- CallbackQueryUserHasNumericStateFilter
@enduml
