@startuml
class UsersAttribute <<sealed>> {
    - OnIds : bool <<get>>
    + UsersAttribute(usernames:string[]?)
    + UsersAttribute(userIds:long[]?)
    <<internal>> UserIds : long[]? <<get>> <<init>>
    <<internal>> Usernames : string[]? <<get>> <<init>>
    # <<internal>> <<override>> GetFilterTypeOf(requestedType:Type) : object
}
AbstractFilterAttribute <|-- UsersAttribute
@enduml
