@startuml
!include ./TelegramUpdater.Hosting/UpdateWriterServiceAbs.puml
!include ./TelegramUpdater.Hosting/UpdaterServiceBuilder.puml
!include ./TelegramUpdater.Hosting/UpdaterServiceExtensions.puml
!include ./TelegramUpdater.Hosting/SimpleWriterService.puml
!include ./TelegramUpdater/GlobalUsings.puml
!include ./TelegramUpdater/Updater.puml
!include ./TelegramUpdater/Filter.puml
!include ./TelegramUpdater/UpdaterOptions.puml
!include ./TelegramUpdater/ApplyFilterAttribute.puml
!include ./TelegramUpdater/FilterCutify.puml
!include ./TelegramUpdater/AbstractPreUpdateProcessor.puml
!include ./TelegramUpdater/UpdaterBuilder.puml
!include ./TelegramUpdater/UpdateWriterAbs.puml
!include ./TelegramUpdater/UpdaterExtensions.puml
!include ./TelegramUpdater/Propagations.puml
!include ./TelegramUpdater/IUpdater.puml
!include ./TelegramUpdater/UpdateContainer/UpdateContainerAbs.puml
!include ./TelegramUpdater/UpdateContainer/IUpdateContainer.puml
!include ./TelegramUpdater/UpdateContainer/IContainer.puml
!include ./TelegramUpdater/FilterAttributes/FilterAttributeBuilder.puml
!include ./TelegramUpdater/FilterAttributes/AbstractFilterAttribute.puml
!include ./TelegramUpdater/Filters/CallbackQueryDataFilter.puml
!include ./TelegramUpdater/Filters/PrivateMessageFilter.puml
!include ./TelegramUpdater/Filters/UserHasNumericStateFilter.puml
!include ./TelegramUpdater/Filters/FromUsersFilter.puml
!include ./TelegramUpdater/Filters/BasicRegexFilter.puml
!include ./TelegramUpdater/Filters/CommandFilter.puml
!include ./TelegramUpdater/Filters/MessageRepliedFilter.puml
!include ./TelegramUpdater/Filters/FromUsernamesFilter.puml
!include ./TelegramUpdater/Filters/MessageTextFilter.puml
!include ./TelegramUpdater/Filters/CommandFilterOptions.puml
!include ./TelegramUpdater/Exceptions/StateKeeperNotRegistried.puml
!include ./TelegramUpdater/Exceptions/CommandDescriptionNotProvided.puml
!include ./TelegramUpdater/ExceptionHandlers/IExceptionHandler.puml
!include ./TelegramUpdater/ExceptionHandlers/CommonExceptions.puml
!include ./TelegramUpdater/ExceptionHandlers/ExceptionHandler.puml
!include ./TelegramUpdater/Helpers/MatchContext.puml
!include ./TelegramUpdater/Helpers/StringConverter.puml
!include ./TelegramUpdater/Helpers/ChatTypeFlags.puml
!include ./TelegramUpdater/Helpers/GridCollection.puml
!include ./TelegramUpdater/UpdateChannels/IGenericUpdateChannel.puml
!include ./TelegramUpdater/UpdateChannels/IUpdateChannel.puml
!include ./TelegramUpdater/UpdateChannels/AbstractChannel.puml
!include ./TelegramUpdater/UpdateWriters/SimpleUpdateWriter.puml
!include ./TelegramUpdater/RainbowUtlities/ProcessorInfo.puml
!include ./TelegramUpdater/RainbowUtlities/ShiningInfo.puml
!include ./TelegramUpdater/RainbowUtlities/Rainbow.puml
!include ./TelegramUpdater/RainbowUtlities/OwnerInfo.puml
!include ./TelegramUpdater/StateKeeping/Extensions.puml
!include ./TelegramUpdater/StateKeeping/IStateKeeper.puml
!include ./TelegramUpdater/StateKeeping/AbstractStateKeeper.puml
!include ./TelegramUpdater/ExtensionMethods/KeyboardsExtensions.puml
!include ./TelegramUpdater/ExtensionMethods/UpdateExtensions.puml
!include ./TelegramUpdater/ExtensionMethods/ExtraDataExtensions.puml
!include ./TelegramUpdater/ExtensionMethods/PropagationExtensions.puml
!include ./TelegramUpdater/ExtensionMethods/ConditionalExtensions.puml
!include ./TelegramUpdater/ExtensionMethods/CommonExtensions.puml
!include ./TelegramUpdater/UpdateHandlers/IUpdateHandler.puml
!include ./TelegramUpdater/UpdateContainer/Extensions/MessageContainerExtensions.puml
!include ./TelegramUpdater/UpdateContainer/Extensions/CallbackQueryContainerExtensions.puml
!include ./TelegramUpdater/UpdateContainer/Extensions/NumericStateKeeperExtensions.puml
!include ./TelegramUpdater/UpdateContainer/UpdateContainers/AnyLiteContainer.puml
!include ./TelegramUpdater/UpdateContainer/UpdateContainers/MessageContainer.puml
!include ./TelegramUpdater/UpdateContainer/UpdateContainers/CallbackQueryContainer.puml
!include ./TelegramUpdater/UpdateContainer/UpdateContainers/AnyContainer.puml
!include ./TelegramUpdater/UpdateContainer/UpdateContainers/RawContainer.puml
!include ./TelegramUpdater/FilterAttributes/Attributes/ChatTypeAttribute.puml
!include ./TelegramUpdater/FilterAttributes/Attributes/UsersAttribute.puml
!include ./TelegramUpdater/FilterAttributes/Attributes/PrivateAttribute.puml
!include ./TelegramUpdater/FilterAttributes/Attributes/RegexAttribute.puml
!include ./TelegramUpdater/FilterAttributes/Attributes/MessageTypeAttribute.puml
!include ./TelegramUpdater/FilterAttributes/Attributes/GroupAttribute.puml
!include ./TelegramUpdater/FilterAttributes/Attributes/UserNumericState.puml
!include ./TelegramUpdater/FilterAttributes/Attributes/RepliedAttribute.puml
!include ./TelegramUpdater/FilterAttributes/Attributes/TextAttribute.puml
!include ./TelegramUpdater/FilterAttributes/Attributes/CommandAttribute.puml
!include ./TelegramUpdater/ExceptionHandlers/Extensions/ExceptionHandlerExtensions.puml
!include ./TelegramUpdater/UpdateChannels/Extensions/ChannelsExtensions.puml
!include ./TelegramUpdater/UpdateChannels/ReadyToUse/PreCheckoutQueryChannel.puml
!include ./TelegramUpdater/UpdateChannels/ReadyToUse/ChosenInlineResultChannel.puml
!include ./TelegramUpdater/UpdateChannels/ReadyToUse/ChatJoinRequestChannel.puml
!include ./TelegramUpdater/UpdateChannels/ReadyToUse/EditedChannelPostChannel.puml
!include ./TelegramUpdater/UpdateChannels/ReadyToUse/MessageChannel.puml
!include ./TelegramUpdater/UpdateChannels/ReadyToUse/EditedMessageChannel.puml
!include ./TelegramUpdater/UpdateChannels/ReadyToUse/PollChannel.puml
!include ./TelegramUpdater/UpdateChannels/ReadyToUse/ShippingQueryChannel.puml
!include ./TelegramUpdater/UpdateChannels/ReadyToUse/PollAnswerChannel.puml
!include ./TelegramUpdater/UpdateChannels/ReadyToUse/ChatMemberChannel.puml
!include ./TelegramUpdater/UpdateChannels/ReadyToUse/MyChatMemberChannel.puml
!include ./TelegramUpdater/UpdateChannels/ReadyToUse/InlineQueryChannel.puml
!include ./TelegramUpdater/UpdateChannels/ReadyToUse/CallbackQueryChannel.puml
!include ./TelegramUpdater/UpdateChannels/ReadyToUse/AnyChannel.puml
!include ./TelegramUpdater/UpdateChannels/ReadyToUse/ChannelPostChannel.puml
!include ./TelegramUpdater/RainbowUtlities/Extensions/RainbowExtensions.puml
!include ./TelegramUpdater/RainbowUtlities/Extensions/ShiningInfoExtensions.puml
!include ./TelegramUpdater/RainbowUtlities/Extensions/ShiningInfoContainerExtensions.puml
!include ./TelegramUpdater/StateKeeping/StateKeepers/AbstractNumericStateKeeper.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/AbstractSingletonUpdateHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/IGenericSingletonUpdateHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ISingletonUpdateHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/IScopedUpdateHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/AbstractScopedUpdateHandlerContainer.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/IGenericScopedUpdateHandlerContainer.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/IScopedUpdateHandlerContainer.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ScopedUpdateHandlerContainerBuilder.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/AbstractScopedUpdateHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Extensions/SingletonUpdateHandlerExtensions.puml
!include ./TelegramUpdater/UpdateHandlers/Extensions/ScopedUpdateHandlersExtensions.puml
!include ./TelegramUpdater/StateKeeping/StateKeepers/NumericStateKeepers/UserNumericStateKeeper.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/Attributes/Extensions.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/Attributes/SingletonHandlerCallbackAttribute.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ReadyToUse/EditedChannelPostHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ReadyToUse/ChosenInlineResultHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ReadyToUse/InlineQueryHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ReadyToUse/PreCheckoutQueryHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ReadyToUse/PollHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ReadyToUse/ShippingQueryHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ReadyToUse/CallbackQueryHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ReadyToUse/EditedMessageHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ReadyToUse/MyChatMemberHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ReadyToUse/ChatJoinRequestHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ReadyToUse/ChatMemberHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ReadyToUse/PollAnswerHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ReadyToUse/AnyHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ReadyToUse/ChannelPostHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Singleton/ReadyToUse/MessageHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ReadyToUse/EditedChannelPostHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ReadyToUse/ChosenInlineResultHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ReadyToUse/InlineQueryHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ReadyToUse/PreCheckoutQueryHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ReadyToUse/PollHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ReadyToUse/ShippingQueryHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ReadyToUse/CallbackQueryHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ReadyToUse/EditedMessageHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ReadyToUse/MyChatMemberHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ReadyToUse/ChatJoinRequestHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ReadyToUse/ChatMemberHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ReadyToUse/PollAnswerHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ReadyToUse/AnyHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ReadyToUse/ChannelPostHandler.puml
!include ./TelegramUpdater/UpdateHandlers/Scoped/ReadyToUse/MessageHandler.puml
@enduml
