@startuml
interface "IStateKeeper`2"<TState,TFrom> {
    + HasAnyState(stateOf:TFrom) : bool
    + GetState(stateOf:TFrom) : TState
    + TryGetState(stateOf:TFrom, theState:TState?) : bool
    + SetState(stateOf:TFrom, theState:TState) : void
    + HasState(stateOf:TFrom, theState:TState) : bool
    + DeleteState(stateOf:TFrom) : bool
}
class "IEquatable`1"<T> {
}
@enduml
