@startuml
class SingletonHandlerCallbackAttribute <<sealed>> {
    + SingletonHandlerCallbackAttribute(updateType:UpdateType)
    + Group : int <<get>> <<set>> = default
}
Attribute <|-- SingletonHandlerCallbackAttribute
SingletonHandlerCallbackAttribute --> "UpdateType" UpdateType
@enduml
