@startuml
abstract class CallbackQueryHandler {
    # CallbackQueryHandler(group:int)
    # Data : string? <<get>>
    # Id : string <<get>>
    # <<async>> AnswerAsync(text:string?, showAlert:bool?, url:string?, cacheTime:int?, cancellationToken:CancellationToken) : Task
}
class "AnyHandler`1"<T> {
}
"AnyHandler`1" "<CallbackQuery>" <|-- CallbackQueryHandler
CallbackQueryHandler --> "From" User
@enduml
