@startuml
enum ChatTypeFlags {
    Private= 2,
    Group= 4,
    Channel= 8,
    SuperGroup= 16,
    Sender= 32,
}
class ChatTypeExtensions <<static>> {
    + {static} Flagable(chatType:ChatType) : ChatTypeFlags
    + {static} IsCorrect(chatType:ChatType, flags:ChatTypeFlags) : bool
}
@enduml
