@startuml
class "MatchContext`1"<TUpdate> <<struct>> {
    <<internal>> MatchContext(simpleContext:IContainer<TUpdate>, isMatched:bool, matchCollection:MatchCollection?)
    + IsMatched : bool <<get>>
    + MatchCollection : MatchCollection? <<get>>
    <<internal>> {static} Check(simpleContext:IContainer<T>, getText:Func<T, string?>, pattern:string, regexOptions:RegexOptions?) : MatchContext<T>
}
class "IContainer`1"<T> {
}
"MatchContext`1" --> "SimpleContext<TUpdate>" "IContainer`1"
@enduml
