@startuml
class StringConverter <<static>> {
    + {static} TryConvert(input:string, type:Type, output:object?) : bool
    + {static} TryConvert(input:string, output:T?) : bool
    + {static} TryConvertArgs(args:string[], output1:T1?, startIndex:int) : bool
    + {static} TryConvertArgs(args:string[], output1:T1?, output2:T2?, startIndex:int) : bool
    + {static} TryConvertArgs(args:string[], output1:T1?, output2:T2?, output3:T3?, startIndex:int) : bool
    + {static} TryConvertArgs(args:string[], output1:T1?, output2:T2?, output3:T3?, output4:T4?, startIndex:int) : bool
}
@enduml
