@startuml
interface IScopedUpdateHandler {
    <<internal>> ExtraData : IReadOnlyDictionary<string, object>? <<get>>
    <<internal>> SetExtraData(extraData:IReadOnlyDictionary<string, object>?) : void
}
IUpdateHandler <|-- IScopedUpdateHandler
@enduml
