@startuml
class "ScopedUpdateHandlerContainerBuilder`2"<THandler,TUpdate> <<sealed>> {
    - <<readonly>> _getT : Func<Update, TUpdate?>?
    + ScopedUpdateHandlerContainerBuilder(updateType:UpdateType, filter:IFilter<TUpdate>?, getT:Func<Update, TUpdate?>?)
    <<internal>> # <<override>> GetT(update:Update) : TUpdate?
}
class "AbstractScopedUpdateHandlerContainer`2"<T1,T2> {
}
"AbstractScopedUpdateHandlerContainer`2" "<THandler,TUpdate>" <|-- "ScopedUpdateHandlerContainerBuilder`2"
@enduml
